Added etcd snapshot timeout parameter
rancher/rke pull request #2418
Opened 2021-01-14 20:36 UTC by rawmind0

Issue https://github.com/rancher/rancher/issues/30663

This PR adds the feature to set etcd snapshot timeout instad of the [default](https://github.com/rancher/rke/blob/v1.1.6/docker/docker.go#L495). 

To limit the changes at the rke logic and functions parameters, the `timeout` argument has been added to cmd/etcd.go and using execution context to propagate the argument. `docker.WaitForContainer` function has been modified to set default `WaitTimeout=300` or timeout provided by context value `wait_timeout` if provided

2021-01-20 14:05 UTC, superseb submitted a review, later dismissed

2021-01-21 19:17 UTC, rawmind0 commented
Merged https://github.com/rancher/types/pull/1196 and updated PR with proper go mod

2021-01-22 06:22 UTC, superseb requested changes
These are my changes after running the following:

```
go get github.com/rancher/types@39b83aaa4bed
go mod vendor
go mod tidy
```

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   go.mod
        modified:   go.sum
        modified:   vendor/github.com/rancher/types/apis/management.cattle.io/v3/backup_types.go
        modified:   vendor/modules.txt

```

2021-01-22 12:09 UTC, rawmind0 commented
You are right @superseb . Updated PR with the proper go mod and vendor files

2021-01-22 12:10 UTC, superseb approved these changes

2021-01-22 14:28 UTC, merged