Switch KDM back to dev-v2.7 branch
rancher/rke pull request #3119
Opened 2022-12-05 23:19 UTC by jiaqiluo

This PR is to bring the latest template for 1.25 into rke 

changes:
- change KDM back to the dev-v2.7 branch
- go generate

Tests:
I used the local build to provision a 1.25 cluster successfully 

```
>  k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.2
```

2022-12-05 23:45 UTC, HarrisonWAffel submitted a review, later dismissed

2022-12-05 23:46 UTC, Oats87 approved these changes

2022-12-05 23:47 UTC, Oats87 commented
@jiaqiluo don’t we normally do go generate in a separate commit?

2022-12-05 23:50 UTC, Oats87 requested changes
Need to split go generate commit out

2022-12-05 23:54 UTC, jiaqiluo commented
the only changes since the previous approvals are splitting commits into two

2022-12-05 23:56 UTC, Oats87 approved these changes

2022-12-06 01:45 UTC, jakefhyde approved these changes

2022-12-06 17:56 UTC, merged