[release v1.5] Add missing calico logs volumeMount
rancher/rke pull request #3403
Opened 2023-09-29 12:01 UTC by chiukapoor

## Issue:
* A missing volumeMount was causing the calico/canal logs to get written to the container overlay filesystem, causing the container to fill up.
* Linked issue: https://github.com/rancher/rancher/issues/40330

## Solution:
* Add missing CNI volume mount and k8s version constraints.
* Patch will apply to newly created nodes with k8s patch version greater than or equal
```
	SeptK8s125Version = "v1.25.14-rancher1-1"
	SeptK8s126Version = "v1.26.9-rancher1-1"
	SeptK8s127Version = "v1.27.6-rancher1-1"
```

2023-10-24 16:07 UTC, manuelbuil approved these changes

2023-10-24 19:32 UTC, jiaqiluo requested changes

2023-10-24 19:32 UTC, jiaqiluo commented on cluster/plan.go
> +			"/var/log/calico/cni:/var/log/calico/cni:z",
Does adding `"/var/log/calico/cni:/var/log/calico/cni:z` here make it always to be in the list of "Binds" which invalidates the above version-checking logic?

2023-10-27 16:07 UTC, snasovich commented
Closing due to linked issue closed.

2023-10-27 16:07 UTC, closed without merging