Add ACI-CNI 6.1.1.2 variables
rancher/rke pull request #3765
Opened 2024-12-31 11:15 UTC by jeffinkottaram

2024-12-31 16:42 UTC, kinarashah requested changes
@jeffinkottaram Could you run `go generate` and commit modified data files

2025-01-06 05:33 UTC, mitulshah-suse commented
@jeffinkottaram KDM changes are merged.. can u update the data files again?

2025-01-06 05:55 UTC, vardhaman22 commented
need to rerun go generate and add these files as well 
```
 types/kdm/zz_generated_deepcopy.go
 types/zz_generated_deepcopy.go
```
 there is a change in copyright comment in these files after doing go generate

2025-01-06 07:53 UTC, jeffinkottaram commented
Added the requested files. PTAL, @mitulshah-suse, @vardhaman22

2025-01-06 13:31 UTC, mitulshah-suse approved these changes
LGTM

2025-01-06 17:34 UTC, kinarashah approved these changes

2025-01-07 04:35 UTC, merged